# 多元回归

## 一、概念

回归（regression）是一种估计变量关系的统计方法。

通过回归可以建立因变量（$Y$）和自变量（$X$）的数量关系，以此进行预测、控制。

因变量（$Y$）通常是连续实数，自变量（$X$）可以是连续的也可以是离散的。

自变量和因变量之间的关系用矩阵进行刻画：$Y = X\beta + \epsilon$，其中$Y$是$n\times 1$的向量，n代表样本数，$X$是$n\times (p+1)$维样本矩阵，p是自变量个数，额外一列是偏置项$x_{i0}=1$，$\beta$是$(p+1)\times 1$维系数向量，$\epsilon$是随机扰动，独立同分布于均值为零的正态分布$N(0,\sigma ^2)$。

用分量刻画则是：$y_i = \beta_0 + \beta_1\times x_1 + ... + \beta_p \times x_p + \epsilon_i$，$\beta_i$是各分量的系数，$\epsilon_i$是第i个样本的随机扰动。

## 二、基本假定

1. $r(X)=p+1<n$，$X$是一个满秩矩阵，且列秩线性无关（变量之间不线性相关），行秩大于列秩（样本数大于变量数+1）
$x_1, x_2, ..., x_p$是确定变量

2. 随机误差项具有零均值和同方差：

$$
\begin{cases}
    E(\epsilon_i) = 0 & i = 1,2,...,n\\
    cov(\epsilon_i, \epsilon_j) = 
    \begin{cases}
        \sigma^2  & i=j \\
        0  & i\neq j
    \end{cases}
\end{cases}
$$

不同样本的随机扰动协方差为零表示不同的样本不相关，在正态假定下即是相互独立

3. 正态性假定：

$$
\begin{cases}
    \epsilon_i \sim N(0, \sigma^2) & i = 1, 2, ..., n\\
    \epsilon_1, \epsilon_2, ... \epsilon_n i.i.d
\end{cases}
$$

由以上假定，结合多元正态分布定义可知

$$
\begin{split}
E(Y) = X\beta \\
var(Y) = \sigma^2 E \\
Y \sim N(X\beta, \sigma^2 E)
\end{split}
$$

## 三、求解

回归系数的求解是回归问题的关键，求解系数矩阵有可以推导的**正规方程**（Normal Equation），也可以根据**损失函数**（loss function）通过**梯度下降**（Gradient Descent）等优化方法极小化损失函数求解。

**损失函数**是衡量**估计值$\hat Y$**（回归结果）和真实数据$Y$差距的函数，在回归问题中常用的损失函数是均方误差（MSE, mean square error）:$\frac 1 2\sum_{i=1}^n (y_i - \hat y_i)^2$

$$
loss =\frac 1 2 \sum_{i=1}^n (y_i - \hat y_i)^2 =\frac 1 2 \sum_{i=1}^n (y_i - \beta_0 - \beta_1\times x_1 - ... - \beta_p \times x_p)^2\\
$$
$$
\begin{cases}
    \frac {\partial loss}{\partial \beta_0} = -\sum_{i=1}^n (y_i - \beta_0 - \beta_1\times x_1 - ... - \beta_p \times x_p) \\
    \frac {\partial loss}{\partial \beta_1} = -\sum_{i=1}^n (y_i - \beta_0 - \beta_1\times x_1 - ... - \beta_p \times x_p)\times x_1 \\
    ... \\
    \frac {\partial loss}{\partial \beta_p} = -\sum_{i=1}^n (y_i - \beta_0 - \beta_1\times x_1 - ... - \beta_p \times x_p)\times x_p
\end{cases}
$$

1. 正规方程

由于损失是关于系数的开口向上的二次函数，因此它的极小值总是存在的，令上式的各个导数均为零。

$$
\begin{cases}
    \frac {\partial loss}{\partial \beta_0}|_{\beta_0 = \hat \beta_0} = -\sum_{i=1}^n (y_i - \hat \beta_0 - \hat \beta_1\times x_1 - ... - \hat \beta_p \times x_p) = 0 \\
    \frac {\partial loss}{\partial \beta_1}|_{\beta_1 = \hat \beta_1} = -\sum_{i=1}^n (y_i - \hat \beta_0 - \hat \beta_1\times x_1 - ... - \hat \beta_p \times x_p)\times x_1 = 0 \\
    ... \\
    \frac {\partial loss}{\partial \beta_p}|_{\beta_p = \hat \beta_p} = -\sum_{i=1}^n (y_i - \hat \beta_0 - \hat \beta_1\times x_1 - ... - \hat \beta_p \times x_p)\times x_p = 0
\end{cases}
$$

整理成向量形式即是：

$$
\begin{split}
X^T(Y-X\beta) = 0\\
X^T Y = X^T X \beta \\
\beta = (X^T X)^{-1}X^T Y
\end{split}
$$

2. 梯度下降

>梯度的本意是一个向量，表示某一函数在该点处的方向导数沿着该方向取得最大(小)值，即函数在该点处沿着该方向（此梯度的方向）变化最快，变化率（梯度的模）最大。

$$
\begin{split}
\nabla \beta = \begin{bmatrix}\
    \frac {\partial loss}{\partial \beta_0}\\
    \frac {\partial loss}{\partial \beta_1}\\
    ...\\
    \frac {\partial loss}{\partial \beta_p}
\end{bmatrix} &= -X^T(Y-\hat Y)\\
Repeat\ until\ convergence: \beta &:= \beta - step\times\nabla\beta \\
\Leftrightarrow Repeat\ for\ every\ j\ until\ convergence: \beta_j &:= \beta_j + step\times\sum_{i=1}^n x_{ij}(y_i - \hat y_i)
\end{split}
$$

## 四、应用

应用数据集是经典的红酒数据集的扩大和更新，因变量是品质（quality），适用于回归和分类问题。

In [1]:
import pandas as pd
import numpy as np
np.random.seed(2099)

white = pd.read_csv('winequality-white.csv', sep=';')
white.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [2]:
x = white.drop(['quality'], axis=1)
x.insert(0, 'bias', 1)
y = white['quality']

n = white.shape[0]
p = white.shape[1]

x = np.array(x).reshape([n, p])
y = np.array(y).reshape([n, 1])

index = np.random.permutation(n)

n_train = int(0.7*n)
n_test = n - n_train

train_index = index[0:n_train]
test_index = index[n_train:n]

train_x = x[train_index,:]
train_y = y[train_index,:]

test_x = x[test_index,:]
test_y = y[test_index,:]

print(white.shape)

(4898, 12)


1. 正规方程

利用公式直接求解

In [3]:
def normal_equation(x, y):
    computation = np.dot(x.T, x)
    computation = np.linalg.inv(computation)
    computation = np.dot(computation, x.T)
    beta = np.dot(computation, y)
    return beta

beta_1 = normal_equation(train_x, train_y)
print(beta_1)

[[ 1.27348050e+02]
 [ 5.04121231e-02]
 [-1.85457189e+00]
 [-4.55813876e-02]
 [ 7.38987163e-02]
 [-3.33457213e-01]
 [ 4.77341398e-03]
 [-3.73433766e-04]
 [-1.27415593e+02]
 [ 6.75370498e-01]
 [ 5.02043717e-01]
 [ 2.28705524e-01]]


计算训练集和测试集损失——均方误差。

在处理均方误差时将平方项的和除以样本数进行规范化，这是因为样本越多损失越大，可以大胆假设一下某个样本集合的损失为定值，那么将样本集合的每个样本重复一遍，损失将会变成原来的2倍，尽管本质上两个样本没有显著区别。

为了对比回归结果在训练集和测试集上的表现，因此需要对损失函数值除以样本数。

In [4]:
def mse(y, y_hat):
    diff = y-y_hat
    MSE = 0.5*np.dot(diff.T, diff)
    return MSE

train_y_hat = np.dot(train_x, beta_1)
test_y_hat = np.dot(test_x, beta_1)

In [5]:
train_loss = mse(train_y, train_y_hat)
print(train_loss/train_y.shape[0])

[[0.28172218]]


In [6]:
test_loss = mse(test_y, test_y_hat)
print(test_loss/test_y.shape[0])

[[0.28249369]]


可以看出，训练集和测试集的损失差别不大，可以认为算法在两个数据集上表现相当，具有良好的泛化能力。

2. 梯度下降求解

梯度下降需要初始化系数矩阵，并在此基础上不断迭代。

In [7]:
def initialize(p):
    return np.random.randn(p).reshape([p, 1])

In [8]:
beta_2 = initialize(p)
print(beta_2)

[[-1.58879755]
 [ 0.27808812]
 [ 0.68357992]
 [-1.12382112]
 [ 1.29198908]
 [-0.50970193]
 [-0.1843707 ]
 [ 0.68305206]
 [ 1.00439464]
 [ 1.86755984]
 [-1.41410639]
 [-0.92758716]]


梯度下降的收敛判断通常是通过损失函数的下降值小于某个阈值$\delta$，推测这种习惯应该源于数学分析。

梯度下降中有两个需要手动设置的超参数，阈值和步长。

In [9]:
def gradient_descent(x, y, beta, delta=0.0001, step=0.5):
    y_hat = np.dot(x, beta)
    
    loss_aft = mse(y, y_hat)
    loss_pre = None

    decay = 1

    while decay>delta:
        loss_pre = loss_aft
        
        gradient = np.dot(x.T, y_hat - y)/y.shape[0]
        beta -= step*gradient
        
        y_hat = np.dot(x, beta)
        loss_aft = mse(y, y_hat)
        
        decay = loss_pre - loss_aft
        print(loss_pre)
        print(loss_aft)
        
        print('decay:'+str(decay))
        #print('loss:'+str(loss_aft))
    
    return beta, loss_aft

beta_2, train_loss_2 = gradient_descent(train_x, train_y, beta_2)

[[14788411.72428423]]
[[1.88523119e+15]]
decay:[[-1.88523117e+15]]


(array([[-4.53235131e+01],
        [-3.01069991e+02],
        [-1.17247540e+01],
        [-1.59183183e+01],
        [-3.25911452e+02],
        [-2.58408950e+00],
        [-1.68681279e+03],
        [-6.72512001e+03],
        [-4.25020094e+01],
        [-1.37455612e+02],
        [-2.29398866e+01],
        [-4.49882796e+02]]), array([[1.88523119e+15]]))

In [13]:
beta_2 = initialize(p)
beta_2, train_loss_2 = gradient_descent(train_x, train_y, beta_2, delta=0.1, step=0.00005)

[[80184218.90502678]]
[[2878380.85411883]]
decay:[[77305838.05090794]]
[[2878380.85411883]]
[[1466769.92558925]]
decay:[[1411610.92852958]]
[[1466769.92558925]]
[[1418985.1604669]]
decay:[[47784.76512235]]
[[1418985.1604669]]
[[1396059.8385283]]
decay:[[22925.3219386]]
[[1396059.8385283]]
[[1373933.30623913]]
decay:[[22126.53228917]]
[[1373933.30623913]]
[[1352167.68155192]]
decay:[[21765.62468722]]
[[1352167.68155192]]
[[1330749.56242189]]
decay:[[21418.11913002]]
[[1330749.56242189]]
[[1309673.26113716]]
decay:[[21076.30128473]]
[[1309673.26113716]]
[[1288933.31558645]]
decay:[[20739.94555071]]
[[1288933.31558645]]
[[1268524.3533319]]
decay:[[20408.96225455]]
[[1268524.3533319]]
[[1248441.08779931]]
decay:[[20083.26553259]]
[[1248441.08779931]]
[[1228678.31686383]]
decay:[[19762.77093548]]
[[1228678.31686383]]
[[1209230.92150018]]
decay:[[19447.39536365]]
[[1209230.92150018]]
[[1190093.86445514]]
decay:[[19137.05704504]]
[[1190093.86445514]]
[[1171262.18894132]]
decay:[[18831.6755138

[[135438.50222687]]
[[133415.67792481]]
decay:[[2022.82430206]]
[[133415.67792481]]
[[131424.92859217]]
decay:[[1990.74933264]]
[[131424.92859217]]
[[129465.74236076]]
decay:[[1959.18623141]]
[[129465.74236076]]
[[127537.61553808]]
decay:[[1928.12682268]]
[[127537.61553808]]
[[125640.05247675]]
decay:[[1897.56306134]]
[[125640.05247675]]
[[123772.56544595]]
decay:[[1867.4870308]]
[[123772.56544595]]
[[121934.674505]]
decay:[[1837.89094095]]
[[121934.674505]]
[[120125.9073789]]
decay:[[1808.76712609]]
[[120125.9073789]]
[[118345.79933591]]
decay:[[1780.108043]]
[[118345.79933591]]
[[116593.89306697]]
decay:[[1751.90626893]]
[[116593.89306697]]
[[114869.73856725]]
decay:[[1724.15449973]]
[[114869.73856725]]
[[113172.89301935]]
decay:[[1696.84554789]]
[[113172.89301935]]
[[111502.92067859]]
decay:[[1669.97234077]]
[[111502.92067859]]
[[109859.39275994]]
decay:[[1643.52791864]]
[[109859.39275994]]
[[108241.88732693]]
decay:[[1617.50543301]]
[[108241.88732693]]
[[106649.98918218]]
decay:[[1

[[16145.28552151]]
[[15994.75356555]]
decay:[[150.53195596]]
[[15994.75356555]]
[[15846.45913982]]
decay:[[148.29442573]]
[[15846.45913982]]
[[15700.36685793]]
decay:[[146.09228189]]
[[15700.36685793]]
[[15556.44189797]]
decay:[[143.92495995]]
[[15556.44189797]]
[[15414.64999356]]
decay:[[141.79190441]]
[[15414.64999356]]
[[15274.9574249]]
decay:[[139.69256866]]
[[15274.9574249]]
[[15137.3310101]]
decay:[[137.6264148]]
[[15137.3310101]]
[[15001.73809656]]
decay:[[135.59291355]]
[[15001.73809656]]
[[14868.14655251]]
decay:[[133.59154405]]
[[14868.14655251]]
[[14736.52475873]]
decay:[[131.62179378]]
[[14736.52475873]]
[[14606.84160032]]
decay:[[129.68315841]]
[[14606.84160032]]
[[14479.06645867]]
decay:[[127.77514165]]
[[14479.06645867]]
[[14353.16920353]]
decay:[[125.89725514]]
[[14353.16920353]]
[[14229.12018521]]
decay:[[124.04901832]]
[[14229.12018521]]
[[14106.8902269]]
decay:[[122.22995832]]
[[14106.8902269]]
[[13986.45061711]]
decay:[[120.43960979]]
[[13986.45061711]]
[[13867.7731

[[5243.43987199]]
[[5234.14925852]]
decay:[[9.29061347]]
[[5234.14925852]]
[[5224.90995128]]
decay:[[9.23930724]]
[[5224.90995128]]
[[5215.72133637]]
decay:[[9.18861492]]
[[5215.72133637]]
[[5206.58280924]]
decay:[[9.13852713]]
[[5206.58280924]]
[[5197.49377457]]
decay:[[9.08903467]]
[[5197.49377457]]
[[5188.45364611]]
decay:[[9.04012846]]
[[5188.45364611]]
[[5179.46184653]]
decay:[[8.99179958]]
[[5179.46184653]]
[[5170.51780729]]
decay:[[8.94403924]]
[[5170.51780729]]
[[5161.62096848]]
decay:[[8.89683881]]
[[5161.62096848]]
[[5152.77077871]]
decay:[[8.85018977]]
[[5152.77077871]]
[[5143.96669495]]
decay:[[8.80408376]]
[[5143.96669495]]
[[5135.20818243]]
decay:[[8.75851252]]
[[5135.20818243]]
[[5126.49471446]]
decay:[[8.71346797]]
[[5126.49471446]]
[[5117.82577235]]
decay:[[8.6689421]]
[[5117.82577235]]
[[5109.20084527]]
decay:[[8.62492708]]
[[5109.20084527]]
[[5100.6194301]]
decay:[[8.58141517]]
[[5100.6194301]]
[[5092.08103133]]
decay:[[8.53839877]]
[[5092.08103133]]
[[5083.58516094]

[[4009.92608046]]
[[4005.13151064]]
decay:[[4.79456982]]
[[4005.13151064]]
[[4000.34853391]]
decay:[[4.78297672]]
[[4000.34853391]]
[[3995.57710176]]
decay:[[4.77143215]]
[[3995.57710176]]
[[3990.81716615]]
decay:[[4.75993561]]
[[3990.81716615]]
[[3986.06867951]]
decay:[[4.74848664]]
[[3986.06867951]]
[[3981.33159474]]
decay:[[4.73708477]]
[[3981.33159474]]
[[3976.6058652]]
decay:[[4.72572953]]
[[3976.6058652]]
[[3971.89144473]]
decay:[[4.71442048]]
[[3971.89144473]]
[[3967.18828757]]
decay:[[4.70315716]]
[[3967.18828757]]
[[3962.49634845]]
decay:[[4.69193913]]
[[3962.49634845]]
[[3957.81558249]]
decay:[[4.68076596]]
[[3957.81558249]]
[[3953.14594528]]
decay:[[4.66963721]]
[[3953.14594528]]
[[3948.4873928]]
decay:[[4.65855248]]
[[3948.4873928]]
[[3943.83988146]]
decay:[[4.64751133]]
[[3943.83988146]]
[[3939.20336809]]
decay:[[4.63651337]]
[[3939.20336809]]
[[3934.57780991]]
decay:[[4.62555818]]
[[3934.57780991]]
[[3929.96316453]]
decay:[[4.61464538]]
[[3929.96316453]]
[[3925.35938998]]

[[3256.1695389]]
[[3253.04722939]]
decay:[[3.1223095]]
[[3253.04722939]]
[[3249.93151392]]
decay:[[3.11571547]]
[[3249.93151392]]
[[3246.82237734]]
decay:[[3.10913658]]
[[3246.82237734]]
[[3243.71980455]]
decay:[[3.10257279]]
[[3243.71980455]]
[[3240.62378051]]
decay:[[3.09602404]]
[[3240.62378051]]
[[3237.53429022]]
decay:[[3.08949029]]
[[3237.53429022]]
[[3234.45131873]]
decay:[[3.08297148]]
[[3234.45131873]]
[[3231.37485116]]
decay:[[3.07646758]]
[[3231.37485116]]
[[3228.30487263]]
decay:[[3.06997853]]
[[3228.30487263]]
[[3225.24136834]]
decay:[[3.06350428]]
[[3225.24136834]]
[[3222.18432354]]
decay:[[3.0570448]]
[[3222.18432354]]
[[3219.13372352]]
decay:[[3.05060002]]
[[3219.13372352]]
[[3216.0895536]]
decay:[[3.04416992]]
[[3216.0895536]]
[[3213.05179917]]
decay:[[3.03775443]]
[[3213.05179917]]
[[3210.02044565]]
decay:[[3.03135352]]
[[3210.02044565]]
[[3206.99547851]]
decay:[[3.02496714]]
[[3206.99547851]]
[[3203.97688326]]
decay:[[3.01859524]]
[[3203.97688326]]
[[3200.96464548]]


[[2743.51695823]]
[[2741.46540331]]
decay:[[2.05155493]]
[[2741.46540331]]
[[2739.41809456]]
decay:[[2.04730875]]
[[2739.41809456]]
[[2737.3750229]]
decay:[[2.04307165]]
[[2737.3750229]]
[[2735.33617929]]
decay:[[2.03884362]]
[[2735.33617929]]
[[2733.30155466]]
decay:[[2.03462462]]
[[2733.30155466]]
[[2731.27114001]]
decay:[[2.03041465]]
[[2731.27114001]]
[[2729.24492634]]
decay:[[2.02621367]]
[[2729.24492634]]
[[2727.22290466]]
decay:[[2.02202168]]
[[2727.22290466]]
[[2725.20506602]]
decay:[[2.01783864]]
[[2725.20506602]]
[[2723.19140147]]
decay:[[2.01366455]]
[[2723.19140147]]
[[2721.1819021]]
decay:[[2.00949937]]
[[2721.1819021]]
[[2719.176559]]
decay:[[2.0053431]]
[[2719.176559]]
[[2717.1753633]]
decay:[[2.0011957]]
[[2717.1753633]]
[[2715.17830613]]
decay:[[1.99705717]]
[[2715.17830613]]
[[2713.18537865]]
decay:[[1.99292748]]
[[2713.18537865]]
[[2711.19657204]]
decay:[[1.98880661]]
[[2711.19657204]]
[[2709.21187749]]
decay:[[1.98469454]]
[[2709.21187749]]
[[2707.23128623]]
decay:[

[[2352.19027618]]
[[2350.94238793]]
decay:[[1.24788824]]
[[2350.94238793]]
[[2349.69703712]]
decay:[[1.24535081]]
[[2349.69703712]]
[[2348.45421838]]
decay:[[1.24281875]]
[[2348.45421838]]
[[2347.21392633]]
decay:[[1.24029204]]
[[2347.21392633]]
[[2345.97615565]]
decay:[[1.23777068]]
[[2345.97615565]]
[[2344.74090099]]
decay:[[1.23525466]]
[[2344.74090099]]
[[2343.50815702]]
decay:[[1.23274396]]
[[2343.50815702]]
[[2342.27791845]]
decay:[[1.23023858]]
[[2342.27791845]]
[[2341.05017995]]
decay:[[1.22773849]]
[[2341.05017995]]
[[2339.82493625]]
decay:[[1.2252437]]
[[2339.82493625]]
[[2338.60218207]]
decay:[[1.22275418]]
[[2338.60218207]]
[[2337.38191214]]
decay:[[1.22026993]]
[[2337.38191214]]
[[2336.1641212]]
decay:[[1.21779094]]
[[2336.1641212]]
[[2334.94880401]]
decay:[[1.21531719]]
[[2334.94880401]]
[[2333.73595533]]
decay:[[1.21284868]]
[[2333.73595533]]
[[2332.52556995]]
decay:[[1.21038538]]
[[2332.52556995]]
[[2331.31764265]]
decay:[[1.2079273]]
[[2331.31764265]]
[[2330.11216823]]

[[2169.01003198]]
[[2168.13191249]]
decay:[[0.87811948]]
[[2168.13191249]]
[[2167.25554968]]
decay:[[0.87636282]]
[[2167.25554968]]
[[2166.38093983]]
decay:[[0.87460985]]
[[2166.38093983]]
[[2165.50807925]]
decay:[[0.87286058]]
[[2165.50807925]]
[[2164.63696427]]
decay:[[0.87111498]]
[[2164.63696427]]
[[2163.7675912]]
decay:[[0.86937307]]
[[2163.7675912]]
[[2162.89995638]]
decay:[[0.86763482]]
[[2162.89995638]]
[[2162.03405614]]
decay:[[0.86590023]]
[[2162.03405614]]
[[2161.16988684]]
decay:[[0.8641693]]
[[2161.16988684]]
[[2160.30744483]]
decay:[[0.86244201]]
[[2160.30744483]]
[[2159.44672647]]
decay:[[0.86071836]]
[[2159.44672647]]
[[2158.58772814]]
decay:[[0.85899833]]
[[2158.58772814]]
[[2157.73044621]]
decay:[[0.85728193]]
[[2157.73044621]]
[[2156.87487706]]
decay:[[0.85556914]]
[[2156.87487706]]
[[2156.0210171]]
decay:[[0.85385996]]
[[2156.0210171]]
[[2155.16886273]]
decay:[[0.85215438]]
[[2155.16886273]]
[[2154.31841034]]
decay:[[0.85045238]]
[[2154.31841034]]
[[2153.46965637]]


[[2030.53353106]]
[[2029.92962643]]
decay:[[0.60390463]]
[[2029.92962643]]
[[2029.32690241]]
decay:[[0.60272402]]
[[2029.32690241]]
[[2028.72535652]]
decay:[[0.60154589]]
[[2028.72535652]]
[[2028.1249863]]
decay:[[0.60037022]]
[[2028.1249863]]
[[2027.52578928]]
decay:[[0.59919702]]
[[2027.52578928]]
[[2026.92776301]]
decay:[[0.59802627]]
[[2026.92776301]]
[[2026.33090504]]
decay:[[0.59685797]]
[[2026.33090504]]
[[2025.73521292]]
decay:[[0.59569212]]
[[2025.73521292]]
[[2025.14068421]]
decay:[[0.59452871]]
[[2025.14068421]]
[[2024.54731646]]
decay:[[0.59336774]]
[[2024.54731646]]
[[2023.95510726]]
decay:[[0.5922092]]
[[2023.95510726]]
[[2023.36405418]]
decay:[[0.59105309]]
[[2023.36405418]]
[[2022.77415479]]
decay:[[0.58989939]]
[[2022.77415479]]
[[2022.18540668]]
decay:[[0.58874811]]
[[2022.18540668]]
[[2021.59780743]]
decay:[[0.58759924]]
[[2021.59780743]]
[[2021.01135465]]
decay:[[0.58645278]]
[[2021.01135465]]
[[2020.42604593]]
decay:[[0.58530872]]
[[2020.42604593]]
[[2019.84187888]

[[1916.77260757]]
[[1916.3873827]]
decay:[[0.38522487]]
[[1916.3873827]]
[[1916.00288194]]
decay:[[0.38450076]]
[[1916.00288194]]
[[1915.61910378]]
decay:[[0.38377816]]
[[1915.61910378]]
[[1915.23604672]]
decay:[[0.38305706]]
[[1915.23604672]]
[[1914.85370927]]
decay:[[0.38233746]]
[[1914.85370927]]
[[1914.47208992]]
decay:[[0.38161935]]
[[1914.47208992]]
[[1914.09118718]]
decay:[[0.38090274]]
[[1914.09118718]]
[[1913.71099957]]
decay:[[0.38018761]]
[[1913.71099957]]
[[1913.3315256]]
decay:[[0.37947397]]
[[1913.3315256]]
[[1912.95276378]]
decay:[[0.37876182]]
[[1912.95276378]]
[[1912.57471263]]
decay:[[0.37805114]]
[[1912.57471263]]
[[1912.19737069]]
decay:[[0.37734195]]
[[1912.19737069]]
[[1911.82073647]]
decay:[[0.37663422]]
[[1911.82073647]]
[[1911.4448085]]
decay:[[0.37592797]]
[[1911.4448085]]
[[1911.06958531]]
decay:[[0.37522318]]
[[1911.06958531]]
[[1910.69506545]]
decay:[[0.37451986]]
[[1910.69506545]]
[[1910.32124744]]
decay:[[0.373818]]
[[1910.32124744]]
[[1909.94812984]]
dec

[[1845.57148802]]
[[1845.31701966]]
decay:[[0.25446836]]
[[1845.31701966]]
[[1845.06300457]]
decay:[[0.25401509]]
[[1845.06300457]]
[[1844.80944181]]
decay:[[0.25356276]]
[[1844.80944181]]
[[1844.55633045]]
decay:[[0.25311136]]
[[1844.55633045]]
[[1844.30366956]]
decay:[[0.25266089]]
[[1844.30366956]]
[[1844.0514582]]
decay:[[0.25221135]]
[[1844.0514582]]
[[1843.79969546]]
decay:[[0.25176274]]
[[1843.79969546]]
[[1843.54838041]]
decay:[[0.25131505]]
[[1843.54838041]]
[[1843.29751212]]
decay:[[0.25086829]]
[[1843.29751212]]
[[1843.04708967]]
decay:[[0.25042245]]
[[1843.04708967]]
[[1842.79711215]]
decay:[[0.24997752]]
[[1842.79711215]]
[[1842.54757864]]
decay:[[0.24953351]]
[[1842.54757864]]
[[1842.29848821]]
decay:[[0.24909042]]
[[1842.29848821]]
[[1842.04983997]]
decay:[[0.24864824]]
[[1842.04983997]]
[[1841.80163299]]
decay:[[0.24820698]]
[[1841.80163299]]
[[1841.55386638]]
decay:[[0.24776662]]
[[1841.55386638]]
[[1841.30653921]]
decay:[[0.24732717]]
[[1841.30653921]]
[[1841.05965058

[[1801.86881181]]
[[1801.68992513]]
decay:[[0.17888667]]
[[1801.68992513]]
[[1801.51133647]]
decay:[[0.17858867]]
[[1801.51133647]]
[[1801.3330452]]
decay:[[0.17829127]]
[[1801.3330452]]
[[1801.15505072]]
decay:[[0.17799448]]
[[1801.15505072]]
[[1800.97735243]]
decay:[[0.17769829]]
[[1800.97735243]]
[[1800.79994972]]
decay:[[0.17740271]]
[[1800.79994972]]
[[1800.62284198]]
decay:[[0.17710774]]
[[1800.62284198]]
[[1800.44602861]]
decay:[[0.17681337]]
[[1800.44602861]]
[[1800.26950902]]
decay:[[0.1765196]]
[[1800.26950902]]
[[1800.09328259]]
decay:[[0.17622643]]
[[1800.09328259]]
[[1799.91734873]]
decay:[[0.17593386]]
[[1799.91734873]]
[[1799.74170684]]
decay:[[0.17564189]]
[[1799.74170684]]
[[1799.56635633]]
decay:[[0.17535051]]
[[1799.56635633]]
[[1799.3912966]]
decay:[[0.17505973]]
[[1799.3912966]]
[[1799.21652705]]
decay:[[0.17476955]]
[[1799.21652705]]
[[1799.0420471]]
decay:[[0.17447995]]
[[1799.0420471]]
[[1798.86785615]]
decay:[[0.17419095]]
[[1798.86785615]]
[[1798.6939536]]
dec

[[1770.52111213]]
[[1770.392397]]
decay:[[0.12871513]]
[[1770.392397]]
[[1770.26387776]]
decay:[[0.12851924]]
[[1770.26387776]]
[[1770.13555401]]
decay:[[0.12832375]]
[[1770.13555401]]
[[1770.00742536]]
decay:[[0.12812865]]
[[1770.00742536]]
[[1769.87949141]]
decay:[[0.12793395]]
[[1769.87949141]]
[[1769.75175177]]
decay:[[0.12773964]]
[[1769.75175177]]
[[1769.62420605]]
decay:[[0.12754572]]
[[1769.62420605]]
[[1769.49685385]]
decay:[[0.1273522]]
[[1769.49685385]]
[[1769.36969478]]
decay:[[0.12715907]]
[[1769.36969478]]
[[1769.24272845]]
decay:[[0.12696633]]
[[1769.24272845]]
[[1769.11595447]]
decay:[[0.12677398]]
[[1769.11595447]]
[[1768.98937245]]
decay:[[0.12658202]]
[[1768.98937245]]
[[1768.86298201]]
decay:[[0.12639044]]
[[1768.86298201]]
[[1768.73678275]]
decay:[[0.12619926]]
[[1768.73678275]]
[[1768.61077429]]
decay:[[0.12600846]]
[[1768.61077429]]
[[1768.48495624]]
decay:[[0.12581805]]
[[1768.48495624]]
[[1768.35932822]]
decay:[[0.12562802]]
[[1768.35932822]]
[[1768.23388985]]


[[1752.17309861]]
[[1752.07119152]]
decay:[[0.10190709]]
[[1752.07119152]]
[[1751.96942629]]
decay:[[0.10176523]]
[[1751.96942629]]
[[1751.86780263]]
decay:[[0.10162366]]
[[1751.86780263]]
[[1751.76632026]]
decay:[[0.10148237]]
[[1751.76632026]]
[[1751.66497889]]
decay:[[0.10134136]]
[[1751.66497889]]
[[1751.56377825]]
decay:[[0.10120064]]
[[1751.56377825]]
[[1751.46271806]]
decay:[[0.1010602]]
[[1751.46271806]]
[[1751.36179802]]
decay:[[0.10092004]]
[[1751.36179802]]
[[1751.26101786]]
decay:[[0.10078016]]
[[1751.26101786]]
[[1751.1603773]]
decay:[[0.10064056]]
[[1751.1603773]]
[[1751.05987606]]
decay:[[0.10050124]]
[[1751.05987606]]
[[1750.95951385]]
decay:[[0.1003622]]
[[1750.95951385]]
[[1750.85929041]]
decay:[[0.10022344]]
[[1750.85929041]]
[[1750.75920545]]
decay:[[0.10008496]]
[[1750.75920545]]
[[1750.6592587]]
decay:[[0.09994675]]


In [14]:
print(train_loss_2/train_y.shape[0])

[[0.51069407]]


可以看出梯度下降的要点在于步长、收敛条件等超参数的设置，步长过长会使得参数变化过大导致损失上升，这在二次函数中十分容易理解，譬如$y=2x^2$，在$y_1 = y(x_1=1)=2$处的梯度为4，步长若设置成1，则$x_2 = x_1 - 4\times1 = -3$，$y_2 = y(x_2=-3) = 18$，递推下去函数值会越来越大。相应地，如果步长设置为0.5，则$x$将永远在+1，-1之间变动。

当我们选取了一个较大的步长时损失可能根本不会下降，当我们选取了一个较大的损失变动阈值和较小的步长时，参数每次变动较小，可能没有训练完全，也即欠拟合。只有步长和阈值均较小时，才能使得参数训练完全，但是同时需要耗费较长时间。

为了进行

In [9]:
def gradient_descent_2(x, y, beta, delta=0.1, step=0.00001):
    y_hat = np.dot(x, beta)
    
    loss_aft = mse(y, y_hat)
    loss_pre = None

    decay = 1
    i=0

    while decay>delta:
        i+=1
        loss_pre = loss_aft
        
        gradient = np.dot(x.T, y_hat - y)/y.shape[0]
        beta -= gradient*(1+1/(2+np.exp(y.shape[0]-i)))*step
        
        y_hat = np.dot(x, beta)
        loss_aft = mse(y, y_hat)
        
        decay = loss_pre - loss_aft
        
        #print(i)
        #print('decay:'+str(decay))
        #print('loss:'+str(loss_aft))
        # spoil alert：加了print之后整个文件大小会激增，而且下个cell的运行时间也会翻倍
    
    return beta, loss_aft



In [10]:
np.random.seed(2099)
beta_2 = initialize(p)
beta_2, train_loss_2 = gradient_descent_2(train_x, train_y, beta_2, delta=0.0001, step=0.00005)
print(train_loss_2/train_y.shape[0])

c:\users\37922\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app


[[0.30090803]]


梯度下降有多种改进方法，主要集中在梯度和步长两个角度，梯度角度的优化在神经网络中运用较多，比如增加动量（momentum）等，这种优化是为了避免困在局部最优解；由于均方误差函数的性质，回归问题存在唯一的最优解，且前期梯度大，后期梯度小形似一个底部平坦四周陡峭的盆地，因此主要考虑通过增加一个单调递增的函数使步长变大的方法加快后期的训练。

这里采用的是类似于logistics回归的函数形式，采用$\frac {1}{2+e^{-x}}$的形式（分母常数如果是1依然存在梯度过大的问题），函数有上确界1/2使后期步长相对于不加函数之前长了0.5倍。

对于多元回归而言求最优解仍然是**建议选用正规方程**求解

参考资料：

[1] 何晓群等 应用回归分析（第三版）[M].北京：中国人民大学出版社，2011